# Generated by Django 4.2 on 2023-04-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_club', models.CharField(max_length=128)),
                ('cat_club', models.CharField(max_length=128)),
                ('info_club', models.TextField()),
                ('day_event', models.DateField()),
                ('time_event', models.TimeField()),
                ('duration_event', models.TimeField()),
            ],
        ),
    ]
