# Generated by Django 4.2 on 2023-04-22 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatClubModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=128, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Категории клубов',
                'verbose_name_plural': 'Категории клубов',
            },
        ),
        migrations.CreateModel(
            name='ClubModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_club', models.CharField(max_length=128)),
                ('info_club', models.TextField()),
                ('days_event', models.CharField(max_length=32, null=True)),
                ('time_start_event', models.TimeField(null=True)),
                ('duration_event', models.TimeField(null=True)),
                ('price_club', models.CharField(max_length=256, null=True)),
                ('cat_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs_app.catclubmodel')),
            ],
            options={
                'verbose_name': 'Клубы',
                'verbose_name_plural': 'Клубы',
            },
        ),
    ]
