# Generated by Django 4.2 on 2023-04-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubmodel',
            options={'verbose_name': 'Клубы', 'verbose_name_plural': 'Клубы'},
        ),
        migrations.RenameField(
            model_name='clubmodel',
            old_name='time_event',
            new_name='time_start_event',
        ),
        migrations.RemoveField(
            model_name='clubmodel',
            name='day_event',
        ),
        migrations.AddField(
            model_name='clubmodel',
            name='days_event',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
