# Generated by Django 4.2 on 2023-04-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs_app', '0002_clubmodel_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubmodel',
            name='duration_event',
        ),
        migrations.RemoveField(
            model_name='clubmodel',
            name='time_start_event',
        ),
        migrations.AddField(
            model_name='clubmodel',
            name='time_event',
            field=models.TimeField(null=True),
        ),
    ]
