# Generated by Django 4.2 on 2023-04-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs_app', '0002_clubmodel_type_club_alter_clubmodel_name_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmodel',
            name='type_club',
            field=models.CharField(choices=[('IT', 'IT'), ('Спорт', 'Спорт'), ('Литература', 'Литература'), ('Рисование', 'Рисование'), ('Культура', 'Культура'), ('Музыка', 'Музыка'), ('Видеоигры', 'Видеоигры'), ('Общение', 'Общение'), ('Рукоделие', 'Рукоделие')], default='IT', max_length=100),
        ),
    ]
