# Generated by Django 4.2 on 2023-04-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs_app', '0003_remove_clubmodel_duration_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmodel',
            name='time_event',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
