# Generated by Django 4.2 on 2023-04-22 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs_app', '0003_catclubmodel_alter_clubmodel_duration_event_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catclubmodel',
            options={'verbose_name': 'Категории клубов', 'verbose_name_plural': 'Категории клубов'},
        ),
        migrations.AddField(
            model_name='clubmodel',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clubmodel',
            name='cat_club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs_app.catclubmodel'),
        ),
    ]
