# Generated by Django 4.2 on 2023-04-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs_app', '0004_alter_catclubmodel_options_clubmodel_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catclubmodel',
            name='cat',
            field=models.CharField(max_length=128, verbose_name='Категория'),
        ),
    ]
