# Generated by Django 4.2 on 2023-04-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs_app', '0004_clubmodel_paid_free_alter_clubmodel_type_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmodel',
            name='info_club',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clubmodel',
            name='paid_free',
            field=models.CharField(choices=[('Не_выбрано', 'Платно или бесплатно:'), ('Платно', 'Платно'), ('Бесплатно', 'Бесплатно')], default='Не_выбрано', max_length=100),
        ),
        migrations.AlterField(
            model_name='clubmodel',
            name='type_club',
            field=models.CharField(choices=[('Тип_не_выбран', 'Тип клуба:'), ('IT', 'IT'), ('Спорт', 'Спорт'), ('Литература', 'Литература'), ('Рисование', 'Рисование'), ('Культура', 'Культура'), ('Музыка', 'Музыка'), ('Видеоигры', 'Видеоигры'), ('Общение', 'Общение'), ('Рукоделие', 'Рукоделие')], default='Тип_не_выбран', max_length=100),
        ),
    ]
