# Generated by Django 4.2 on 2023-04-23 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs_app', '0005_alter_clubmodel_options_alter_clubmodel_days_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmodel',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_system', to=settings.AUTH_USER_MODEL),
        ),
    ]
