# Generated by Django 4.2 on 2023-04-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs_app', '0008_catclubmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catclubmodel',
            name='image',
            field=models.FileField(null=True, upload_to='photos/'),
        ),
    ]
