# Generated by Django 4.2 on 2023-04-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs_app', '0010_alter_catclubmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmodel',
            name='slug_club',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
