# Generated by Django 4.2 on 2023-05-01 17:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs_app', '0013_articleclub_author_club'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleclub',
            options={'verbose_name': 'Статьи клубов', 'verbose_name_plural': 'Статьи клубов'},
        ),
        migrations.RemoveField(
            model_name='articleclub',
            name='text',
        ),
        migrations.AddField(
            model_name='articleclub',
            name='text_body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
