# Generated by Django 4.2 on 2023-05-02 13:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs_app', '0016_rename_author_articleclubmodel_author_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleclubmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='articles/', verbose_name='Главное изображение статьи'),
        ),
        migrations.AlterField(
            model_name='articleclubmodel',
            name='text_body',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Контент статьи'),
        ),
        migrations.AlterField(
            model_name='articleclubmodel',
            name='title_article',
            field=models.CharField(max_length=128, unique=True, verbose_name='Заголовок статьи'),
        ),
    ]
