# Generated by Django 4.2 on 2023-05-03 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs_app', '0017_alter_articleclubmodel_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articleclubmodel',
            old_name='slug',
            new_name='slug_article',
        ),
    ]
