# Generated by Django 4.2 on 2023-05-03 14:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs_app', '0018_rename_slug_articleclubmodel_slug_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_msg', models.SlugField(max_length=512, unique=True)),
                ('title_msg', models.CharField(max_length=128)),
                ('date_load', models.DateField(default=datetime.date(2023, 5, 3))),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
                ('sender_club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs_app.clubmodel')),
            ],
        ),
    ]
