# Generated by Django 4.2 on 2023-05-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs_app', '0019_messageclub'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageclub',
            name='body_msg',
            field=models.TextField(null=True),
        ),
    ]
