# Generated by Django 4.2 on 2023-05-03 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs_app', '0020_messageclub_body_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageclub',
            name='body_msg',
            field=models.TextField(null=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='messageclub',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messageclub',
            name='title_msg',
            field=models.CharField(max_length=128, verbose_name='Заголовок сообщения'),
        ),
    ]
