# Generated by Django 4.2 on 2023-05-07 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs_app', '0021_alter_messageclub_body_msg_alter_messageclub_sender_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messageclub',
            options={'verbose_name': 'Сообщения клубов', 'verbose_name_plural': 'Сообщения клубов'},
        ),
        migrations.AlterField(
            model_name='messageclub',
            name='date_load',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='messageclub',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Отправитель'),
        ),
        migrations.AlterField(
            model_name='messageclub',
            name='sender_club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs_app.clubmodel', verbose_name='Клуб'),
        ),
    ]
