# Generated by Django 4.2 on 2023-05-08 16:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs_app', '0023_alter_messageclub_title_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleclubmodel',
            name='text_body',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Контент статьи'),
        ),
    ]
