# Generated by Django 4.2 on 2023-05-08 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs_app', '0024_alter_articleclubmodel_text_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articleclubmodel',
            old_name='slug_article',
            new_name='slug_content',
        ),
        migrations.RenameField(
            model_name='messageclub',
            old_name='slug_msg',
            new_name='slug_content',
        ),
    ]
