# Generated by Django 4.2 on 2023-05-08 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs_app', '0025_rename_slug_article_articleclubmodel_slug_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messageclub',
            old_name='sender',
            new_name='author_user',
        ),
        migrations.RenameField(
            model_name='messageclub',
            old_name='sender_club',
            new_name='club_contains',
        ),
    ]
