# Generated by Django 4.2 on 2023-05-15 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duty_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActivePerson',
            new_name='Person',
        ),
    ]
