# Generated by Django 4.2 on 2023-05-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty_app', '0002_rename_activeperson_person'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Участники', 'verbose_name_plural': 'Участники'},
        ),
        migrations.AlterField(
            model_name='person',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Дежурил'),
        ),
    ]
