# Generated by Django 4.2 on 2023-05-15 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duty_app', '0003_alter_person_options_alter_person_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='PersonModel',
        ),
    ]
