# Generated by Django 4.2 on 2023-05-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty_app', '0004_rename_person_personmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='personmodel',
            name='date_load',
            field=models.DateField(null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='active',
            field=models.BooleanField(default=False, null=True, verbose_name='Дежурил'),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='name',
            field=models.CharField(max_length=128, null=True, verbose_name='Ученик'),
        ),
    ]
