# Generated by Django 4.2 on 2023-05-15 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duty_app', '0005_personmodel_date_load_alter_personmodel_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personmodel',
            old_name='date_load',
            new_name='date_duty',
        ),
    ]
