# Generated by Django 4.2 on 2023-05-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty_app', '0006_rename_date_load_personmodel_date_duty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personmodel',
            name='date_duty',
            field=models.DateTimeField(null=True, verbose_name='Дата'),
        ),
    ]
